package isel.casciffo.casciffospringbackend.states.state

import kotlin.math.abs

enum class States {
    SUBMETIDO,VALIDACAO_CF,VALIDACAO_INTERNA_DEPARTMENTS,
    VALIDACAO_EXTERNA, SUBMISSAO_AO_CA, VALIDACAO_INTERNA_CA, VALIDADO,
    CANCELADO, COMPLETO, ATIVO, INDEFERIDO, VALIDACAO_INTERNA_UIC;
}