package isel.casciffo.casciffospringbackend.proposals.comments

import org.springframework.data.repository.reactive.ReactiveSortingRepository
import org.springframework.stereotype.Repository

@Repository
interface ProposalCommentsRepository: ReactiveSortingRepository<ProposalComment, Int>