package isel.casciffo.casciffospringbackend.common

enum class NotificationType {
    PROPOSAL_SUBMITTED, PROPOSAL_DETAILS, PROPOSAL_FINANCE, PROPOSAL_EVENTS, PROPOSAL_OBSERVATION, PROPOSAL_CONTACT,
    RESEARCH_DETAILS, RESEARCH_VISIT,
    USER_NEW_ROLES
}